name: pytopocomplexity
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - rasterio
  - dask
  - matplotlib
  - tqdm
  - numba
  - jupyter
  - jupyterlab
  - notebook
  - ipywidgets
  - landlab
  - gdal
  - geopandas
  - scikit-image
  - statsmodels
  - pip
  - pip:
    - pytopocomplexity